name: Docker Image CI
on:
  push:
    branches: [ "main" ]
jobs:
  build-login-push:
    runs-on: ubuntu-latest
    environment: actions-env
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build . -t "${{ vars.DOCKERHUB_USERNAME }}/memorizing-words:latest"
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PAT }}
      - name: Push to Docker Hub
        run: docker push "${{ vars.DOCKERHUB_USERNAME }}/memorizing-words:latest"
